# Generated by Django 5.1.2 on 2024-11-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=255)),
                ("major", models.IntegerField()),
                ("minor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("povis_id", models.CharField(max_length=32)),
                ("app_version", models.CharField(max_length=16)),
                ("locale", models.CharField(max_length=5)),
                ("mac_address", models.CharField(max_length=17)),
                ("type", models.IntegerField()),
                ("version", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("term", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("building", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start", models.DateTimeField()),
                ("session_end", models.DateTimeField()),
                ("attendance_start", models.DateTimeField()),
                ("attendance_end", models.DateTimeField()),
                ("late_start", models.DateTimeField()),
                ("late_end", models.DateTimeField()),
                ("absence_start", models.DateTimeField()),
                ("absence_end", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=16)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
            ],
            options={
                "unique_together": {("protocol", "host", "port")},
            },
        ),
    ]
