# Generated by Django 5.1.2 on 2024-11-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ble",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.session"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.session"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.lecture"
            ),
        ),
    ]
