# Generated by Django 5.1.2 on 2024-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_ble_session_alter_room_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="code",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
    ]
