# Generated by Django 5.1.3 on 2024-11-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_session_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ble",
            name="session",
        ),
        migrations.AddField(
            model_name="session",
            name="ble",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="attendance.ble",
            ),
        ),
    ]
