services:
  web:
    build:
      context: ../../
      dockerfile: apps/automata/Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && uvicorn automata.asgi:application --host 0.0.0.0 --port 8000"
    environment:
      - DJANGO_SETTINGS_MODULE=automata.production_settings
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - django-secret-key
      - database-password
    depends_on:
      - database
      - redis
      - scheduler
      - worker
      - migrator
    restart: unless-stopped
  scheduler:
    build:
      context: ../../
      dockerfile: apps/automata/Dockerfile
    command: celery -A automata beat -l info -S django
    environment:
      - DJANGO_SETTINGS_MODULE=automata.production_settings
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - django-secret-key
      - database-password
    depends_on:
      - database
      - redis
      - worker
      - migrator
    restart: unless-stopped
  worker:
    build:
      context: ../../
      dockerfile: apps/automata/Dockerfile
    command: celery -A automata worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=automata.production_settings
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - django-secret-key
      - database-password
    depends_on:
      - database
      - redis
      - migrator
    restart: unless-stopped
  migrator:
    build:
      context: ../../
      dockerfile: apps/automata/Dockerfile
    command: python manage.py migrate
    environment:
      - DJANGO_SETTINGS_MODULE=automata.production_settings
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django-secret-key
      - DATABASE_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - django-secret-key
      - database-password
    depends_on:
      - database
  database:
    image: postgres:17
    volumes:
      - automata-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=automata
      - POSTGRES_USER=automata
      - POSTGRES_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - database-password
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    volumes:
      - automata-redis:/data
    restart: unless-stopped

volumes:
  automata-database:
  automata-redis:


secrets:
  database-password:
    file: .secrets/database-password.txt
  django-secret-key:
    file: .secrets/django-secret-key.txt
